function participants = IRSST_participants(varargin)
% participants with '1' are blacklisted
% add 'IRSST' to include IRSST_SujeTd'

participants = [
    ['sarc' '1'];...
    ['inea' '1'];...
    ['dapo' '1'];...
    ['laug' '1'];...
    ['mara' '1'];...
    ['mars' '1'];...
    ['yosc' '1'];...
    ['marc' '1'];...
    ['benl' '1'];...
    ['davo' '1'];...
    ['marb' '1'];...
    ['gatb' '1'];...
    ['yoap' '1'];...
    ['romm' '1'];...
    ['camb' '1'];...
    ['eved' '1'];...
    ['naus' '1'];...
    ['emid' '1'];...
    ['verc' '1'];...
    ['marh' '1'];...
    ['samn' '1'];...
    ['alef' '1'];...
    ['danf' '1'];...
    ['aimq' '1'];...
    ['ameg' '1'];...
    ['noel' '1'];...
    ['karm' '1'];...
    ['patm' '1'];...
    ['vicj' '1'];...
    ['luia' '1'];...
    ['gabf' '1'];...
    ['aleb' '1'];...
    ['humm' '0'];...
    ['emmb' '1'];...
    ['fabg' '1'];...
    ['nicl' '1'];...
    ['sylg' '1'];...
    ['daml' '1'];...
    ['land' '0'];...
    ['emyc' '1'];...
    ['amia' '1'];...
    ['romr' '1'];...
    ['carb' '1'];...
    ['anns' '1'];...
    ['steb' '1'];...
    ['chac' '1'];...
    ['roxd' '1'];...
    ['vivs' '1'];...
    ['adrc' '1'];...
    ['geoa' '1'];...
    ['yoab' '1'];...
    ['nemk' '1'];...
    ['matr' '1'];...
    ['doca' '1'];...
    ['jawr' '1'];...
    ['fabd' '1'];...
    ['damg' '1'];...
    ['arst' '1'];...
    ['phil' '1'];...
    ['marm' '1'];...
    ];

blacklist = participants(:,5) == '0';
participants(blacklist,:) = [];

if nargin > 0 && contains(varargin, 'IRSST')
    temp(:,:) = strcat('IRSST_',[upper(participants(:,1)) participants(:,2:end-2) upper(participants(:,end-1))]);
    participants = cellstr(temp(:,1:end));
elseif nargin > 0 && contains(varargin, 'weight')
    temp(:,:) = strcat('IRSST_',[upper(participants(:,1)) participants(:,2:end-2) upper(participants(:,end-1))]);
    participants = cellstr(temp(:,1:end));
    weight = [55.5 55.8 61.4 66 56.7 54 63 70 67 86 68 94 79 91 65.9 65 87.5 51 68 61 51.5 52.3 60 54 72 63.5 65 85 69 ...
        72 76 47 70 69.1 74 78 79 73 73 61.5 50 63 60 62 57 58 56 70 72 64 70 75 68 65 83 73 100 75 65 70];
    weight(blacklist) = [];
    participants(:,2) = num2cell(weight,1);
    
else
    participants = cellstr(participants(:,1:end-1));
end
