%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  ____                       _         __  __            _   _                  %
% |  _ \ ___  _ __ ___   __ _(_)_ __   |  \/  | __ _ _ __| |_(_)_ __   ___ ____  %
% | |_) / _ \| '_ ` _ \ / _` | | '_ \  | |\/| |/ _` | '__| __| | '_ \ / _ \_  /  %
% |  _ < (_) | | | | | | (_| | | | | | | |  | | (_| | |  | |_| | | | |  __// /   % 
% |_| \_\___/|_| |_| |_|\__,_|_|_| |_| |_|  |_|\__,_|_|   \__|_|_| |_|\___/___|  %
%                                                                                %  
% Auteur : Romain Martinez                                 Date : Juin 2016      %
% Description : Fonction pour générer GUI attribution des data pour a_col_assign %
% Input : fichier c3d                                                            % 
% Output : attribution des voies du fichier c3d                                  %                                      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
						  
Muscle_list = {'Delt_Ant';
               'Delt_Med';
               'Delt_Post';
               'Biceps';
               'Triceps';
               'Trap_Up';
               'Trap_Inf';
               'Gd_Dent';
               'Supra';
               'Infra';
               'Subscap';
               'Pec';
               'Gd_Dors';          
               'Force_1';
               'Force_2';
               'Force_3';
               'Force_4';
               'Force_5';
               'Force_6'};
           
index = 1
    % Figure
    S.fh = figure('units','pixels',...
                  'position',[500 500 500 500],...
                  'menubar','none',...
                  'numbertitle','off',...
                  'resize','off');
    % List
    S.ls = uicontrol('style','list',...
                     'unit','pix',...
                     'position',[10 70 200 400],...
                     'min',0,'max',2,...
                     'fontsize',14,...
                     'string',fields);
    % Bouton
    S.pb = uicontrol('style','push',...
                     'units','pix',...
                     'position',[230 430 180 40],...
                     'fontsize',14,...
                     'string',Muscle_list(index),...
                     'Callback','GUI_OrgData_Next'); 
    
    S.pc = uicontrol('style','push',...
                     'units','pix',...
                     'position',[230 380 100 40],...
                     'fontsize',14,...
                     'string','NaN',...
                     'Callback','GUI_OrgData_NaN'); 